image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test

variables:
    PSQL_VERSION: "9.6"
    VERSION: "10.0"
    TRAVIS_PYTHON_VERSION: "2.7"
    ODOO_REPO: "vauxoo/odoo"
    ODOO_BRANCH: "10.0"
    BASE_IMAGE: "vauxoo/odoo-100-image"
    COUNTRY: "MX"

lint:
  stage: test
  tags:
    - lint
  variables:
    http_proxy: http://172.17.0.1:3128
    https_proxy: http://172.17.0.1:3128
    ftp_proxy: http://172.17.0.1:3128
    LINT_CHECK: "0"
    TESTS: "0"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests

test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  tags:
    - odoo
    - test
  variables:
    http_proxy: http://172.17.0.1:3128
    https_proxy: http://172.17.0.1:3128
    ftp_proxy: http://172.17.0.1:3128
    LINT_CHECK: "0"
    TESTS: "0"
    INCLUDE: "hiperauto"
    INSTALL: "hiperauto"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - apt update && apt install -y libevent-dev libjpeg-dev libldap2-dev libsasl2-dev libssl-dev libffi-dev libpq-dev libx11-6 libxext6 libxml2-dev libxrender1 libxslt-dev python-dev swig xmlstarlet xsltproc
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc || true
